const IMG = {
    jammmingLogo: new URL('./branding/00_jammming-logo.png', import.meta.url).href,  
    spotifyLogo: new URL('./branding/00_spotify-logo.png', import.meta.url).href,  

    plusPNG: new URL('./symbols/02_plus-symbol.png', import.meta.url).href,
    minusPNG: new URL('./symbols/02_minus-symbol.png', import.meta.url).href,
    plus2PNG: new URL('./symbols/02_plus2-symbol.png', import.meta.url).href,
    plus2GreenPNG: new URL('./symbols/02_plus2-symbol-green.png', import.meta.url).href,
    plus2GreyPNG: new URL('./symbols/02_plus2-symbol-grey.png', import.meta.url).href,
    plus2BlackPNG: new URL('./symbols/02_plus2-symbol-black.png', import.meta.url).href,
    plusMenuPNG: new URL('./symbols/02_plusMenu-symbol.png', import.meta.url).href,
    plusMenuGreenPNG: new URL('./symbols/02_plusMenu-symbol-green.png', import.meta.url).href,
    minus2PNG: new URL('./symbols/02_minus2-symbol.png', import.meta.url).href,
    gobackPNG: new URL('./symbols/01_arrow-symbol.png', import.meta.url).href,
    gofowardPNG: new URL('./symbols/01_right-arrow.png', import.meta.url).href,
    upAndDownPNG: new URL('./symbols/01_up-and-down.png', import.meta.url).href,
    pencilPNG: new URL('./symbols/04_pencil.png', import.meta.url).href,
    sharePNG: new URL('./symbols/05_share.png', import.meta.url).href,
    trashBinPNG: new URL('./symbols/06_bin-symbol.png', import.meta.url).href,
    dragPNG: new URL('./symbols/01_drag.png', import.meta.url).href,
    greenDragPNG: new URL('./symbols/01_green-drag.png', import.meta.url).href,
    blackDragPNG: new URL('./symbols/01_black-drag.png', import.meta.url).href,
    optionsPNG: new URL('./symbols/01_interface.png', import.meta.url).href,
    searchPNG: new URL('./symbols/03_search.png', import.meta.url).href,
    clockPNG: new URL('./symbols/10_clock.png', import.meta.url).href,
    placeHolders: new URL('./symbols/16_place-holder.png', import.meta.url).href,
    profilePlaceHolder: new URL('./symbols/16_profile-place-holder.png', import.meta.url).href,
    emptyPlaylistPlaceHolder: new URL('./symbols/17_empty-playlist-place-holder.png', import.meta.url).href,


    volumePNG: new URL('./symbols/11_volume.png', import.meta.url).href,
    mutePNG: new URL('./symbols/11_mute.png', import.meta.url).href,
    previousPNG: new URL('./symbols/12_back-button.png', import.meta.url).href,
    nextPNG: new URL('./symbols/12_next-button.png', import.meta.url).href,
    pausePNG: new URL('./symbols/13_pause-button.png', import.meta.url).href,
    pausePNG2: new URL('./symbols/13_pause-button2.png', import.meta.url).href,
    pausePNG2Green: new URL('./symbols/13_pause-button2-green.png', import.meta.url).href,
    pausePNG2Black: new URL('./symbols/13_pause-button2-black.png', import.meta.url).href,
    playPNG: new URL('./symbols/13_play-button.png', import.meta.url).href,
    play2PNG: new URL('./symbols/13_play-button2.png', import.meta.url).href,
    play3PNG: new URL('./symbols/13_play-button3.png', import.meta.url).href,
    playPNG2Green: new URL('./symbols/13_play-button2-green.png', import.meta.url).href,
    playPNG2Black: new URL('./symbols/13_play-button2-black.png', import.meta.url).href,
    play3PNGGreen: new URL('./symbols/13_play-button3-green.png', import.meta.url).href,
    norepeatPNG: new URL('./symbols/14_repeat.png', import.meta.url).href,
    repeatPNG: new URL('./symbols/14_repeat-green.png', import.meta.url).href,
    noshufflePNG: new URL('./symbols/15_shuffle.png', import.meta.url).href,
    shufflePNG: new URL('./symbols/15_shuffle-green.png', import.meta.url).href,

    unsavedPNG: new URL('./symbols/07_checked.png', import.meta.url).href,
    savedPNG: new URL('./symbols/07_checked-green.png', import.meta.url).href,
    cautionPNG: new URL('./symbols/09_caution-symbol.png', import.meta.url).href,

    spotifySearchPNG: new URL('./pictures/spotify-glass.png', import.meta.url).href,
    spotifySearch2PNG: new URL('./pictures/spotify-glass2.png', import.meta.url).href,
    glassSearchPNG: new URL('./pictures/search-glass.png', import.meta.url).href,
    notFound2PNG: new URL('./pictures/no-results.png', import.meta.url).href,

    rhcpPNG: new URL('./background/01_rhcp-placeholder.jpg', import.meta.url).href,
};

export default IMG;